spring.application.name: continuum-base-worker

spring:
  cloud:
    stream:
      binders:
        main-kafka-cluster:
          type: kafka
          default-candidate: false
          environment:
            spring.cloud.stream.kafka:
              binder:
                brokers: ${CONTINUUM_KAFKA_MAIN_BROKER_LIST:localhost:39092,localhost:39093,localhost:39094}
                consumer-properties:
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  # value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                  value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                  schema.registry.url: ${CONTINUUM_KAFKA_MAIN_SCHEMA_REGISTRY:http://localhost:38080} # Not required yet
                  specific.avro.reader: true
                  auto.offset.reset: latest
                  fetch.max.wait.ms: 40000
                  request.timeout.ms: 60000
                producer-properties:
                  key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  # value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
                  schema.registry.url: ${CONTINUUM_KAFKA_MAIN_SCHEMA_REGISTRY:http://localhost:38080} # Not required yet
                  max.request.size: 104857600
                dlq-producer-properties:
                  key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  # value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
                  schema.registry.url: ${CONTINUUM_KAFKA_MAIN_SCHEMA_REGISTRY:http://localhost:38080} # Not required yet
                  max.request.size: 104857600
      bindings:
        continuum-core-event-WorkflowExecutionSnapshot-output:
          binder: main-kafka-cluster
          destination: continuum-core-event-WorkflowExecutionSnapshot
          content-type: application/json
          producer:
            use-native-encoding: true
        continuum-core-event-FeatureRegistration-output:
          binder: main-kafka-cluster
          destination: continuum-core-event-FeatureRegistration
          content-type: application/json
          producer:
            use-native-encoding: true
      kafka:
        bindings:
          continuum-core-event-FeatureRegistration-output:
            producer:
              configuration:
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: ${CONTINUUM_KAFKA_MAIN_SCHEMA_REGISTRY:http://localhost:38080}
                specific.avro.reader: true
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}
    connection:
      target: ${TEMPORAL_SERVER_ADDRESS:localhost:7233}
    workersAutoDiscovery:
      packages: org.projectcontinuum.core.worker
continuum.core:
  worker:
    node-task-queue: ${CONTINUUM_NODE_TASK_QUEUE:continuum-node-task-queue}
    cache-storage-path: ${CONTINUUM_CACHE_STORAGE_PATH:./.continuum-cache/workflow-data}
    knime:
      executable-path: ${CONTINUUM_KNIME_EXECUTABLE_PATH:/opt/knime/knime}
      workflow-storage-path: ${CONTINUUM_KNIME_WORKFLOW_STORAGE_PATH:./.continuum-cache/knime-workflows}
      workspace-storage-path: ${CONTINUUM_KNIME_WORKSPACE_STORAGE_PATH:./.continuum-cache/knime-workspaces}
    storage:
      type: ${CONTINUUM_STORAGE_TYPE:minio}
      bucket-name: ${CONTINUUM_CACHE_BUCKET_NAME:continuum-worker-storage}
      bucket-region: ${CONTINUUM_CACHE_BUCKET_REGION:us-east-2}
      bucket-base-path: ${CONTINUUM_CACHE_BUCKET_BASE_PATH:workflow-data}
      minio:
        endpoint: ${CONTINUUM_MINIO_ENDPOINT:http://localhost:39000}
        access-key: ${CONTINUUM_MINIO_USERNAME:minioadmin}
        secret-key: ${CONTINUUM_MINIO_PASSWORD:minioadmin}
logging:
  level:
    root: error
    org.projectcontinuum.core.worker: info
    org.projectcontinuum.core.commons.node: info
    org.projectcontinuum.core: info
    org.projectcontinuum.feature.ai: debug
    org.projectcontinuum.core.worker.activity: debug